### ISSUE TITLE
Report-uri path

### ISSUE THREAD

**Issue by sbrewell** [NWebsec/Docs#2]
Hi. I've checked with w3c today, and the URI can be absolute as well as relative, so the following statement is incorrect.

"The report-uri must be a relative URI, so you might have to include a report handler in every one of your applications (unless they're running on the same domain)."

Cheers

**Comment by ScottHelme** [comment]
Checking in on the thread :)

**Comment by klings** [comment]
Docs weren't 100% correct, absolute report URIs have been supported since I added CSP 2 support. I'll update the docs.

**Comment by klings** [comment]
FYI, the change does not show up when visiting the 4.2 docs, which are default when visiting docs.nwebsec.com. I'm having trouble resetting my password with RTD and getting back into my account. I'll get the versions sorted when I regain access.

The change shows up here: https://docs.nwebsec.com/en/latest/nwebsec/Configuring-csp.html
